app:
  appName: Chassis - Clean Architecture - NodeJS
  description: Chassis using Clean Architecture in NodeJS
  environment: dev
log:
  level: debug # modes available orderer by magnitude: error, warning, info, debug
express:
  enableCors: false
  timeout: 10s