openapi: 3.0.0
info:
  title: Chassis Clean Architecture NodeJS
  description: Chassis for NodeJS using Clean Architecture
  version: 0.1.0

paths:

  /healthcheck:
    get:
      summary: Healthcheck of the application
      tags:
        - "Healthcheck"
      operationId: check
      responses: 
        "200": 
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                message: 'OK'
        "500":
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InnerErrorResponse'
              example:
                code: 500
                message: Internal Error
  
  /config:
    get:
      summary: Get the application configuration. Don't expose this method in production environment!!!
      tags:
        - "Configuration"
      operationId: getConfig
      responses: 
        "200": 
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponse'
              example:
                message: 'OK'
        "500":
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InnerErrorResponse'
              example:
                code: 500
                message: Internal Error

servers:
  - url: /api

components:
  schemas:

    # RESPONSES

    SuccessResponse:
      type: object
      properties:
        message:
          type: string

    ObjectResponse:
      type: object

    InnerErrorResponse:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
